<?php

/**
 * @file
 * Contains varnish_image_purge.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Entity\EntityInterface;
use GuzzleHttp\Client;

/**
 * Implements hook_help().
 */
function varnish_image_purge_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the varnish_image_purge module.
    case 'help.page.varnish_image_purge':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Purge image styles after entity update') . '</p>';
      $output .= '<p>' . t('You need to setup Varnish to listen to the request method URIBAN. Example:') . '</p>';
      $output .= '<pre><code>if (req.method == "URIBAN") {<br />';
      $output .= '  ban("req.http.host == " + req.http.host + " && req.url == " + req.url);<br />';
      $output .= '  # Throw a synthetic page so the request won\'t go to the backend.<br />';
      $output .= '  return (synth(200, "Ban added."));<br />';
      $output .= '}</code></pre>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_update().
 *
 */
function varnish_image_purge_entity_update(EntityInterface $entity) {

  $bundle = $entity->bundle();
  $type = $entity->getEntityTypeId();
  $entitymanager = \Drupal::service('entity_field.manager');

  $class = \Drupal::entityTypeManager()
    ->getDefinition($type)
    ->getOriginalClass();
  $interface = 'Drupal\Core\Entity\FieldableEntityInterface';

  if (in_array($interface, class_implements($class))) {
    $field_definitions = $entitymanager->getFieldDefinitions($type, $bundle);
    if (isset($field_definitions)) {
      $field_images = [];
      foreach ($field_definitions as $field_definition) {
        /* @var $field_definition Drupal\field\Entity\FieldConfig; */
        if ($field_definition->getType() == 'image') {
          $field_images[] = $field_definition->getName();
        }
      }
      if (count($field_images) > 0) {
        $client = new Client();
        $styles = ImageStyle::loadMultiple();
        foreach ($field_images as $field_image) {
          $file = File::load($entity->$field_image->getValue()[0]['target_id']);

          foreach ($styles as $style) {
            /* @var $style Drupal\image\Entity\ImageStyle; */
            try {
              $request = $client->request('URIBAN', $style->buildUrl($file->getFileUri()));
            }
            catch (Exception $e) {
              \Drupal::logger('varnish_image_purge')
                ->error('URL not purged ' . $style->buildUrl($file->getFileUri()) . $e->getMessage());
            }
          }
        }
      }
    }
  }
}
