<?php

/**
 * @file
 * Contains varnish_image_purge.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_update().
 */
function varnish_image_purge_entity_update(EntityInterface $entity) {
  /** @var \Drupal\varnish_image_purge\VarnishImageQueuerInterface $queuer */
  $queuer = \Drupal::service('varnish_image_purge.varnish_image_queuer');

  // Invalidate entity images.
  $queuer->invalidate($entity);
}
